version: '3'

services:
  web:
    build: .
    volumes:
      - ./static:/static
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./static:/static
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/logs:/var/log/letsencrypt
  #     - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt